### ISSUE TITLE
代码建议

### ISSUE THREAD

**Issue by zgayjjf** [nanjixiong218/analys-middlewares#1]
文中代码有误。

```javascript
   while(idx < stack.length) {
      mid = stack[idx++];
      mid(req, res, next);
    }
```
按照这里的简化代码，next根本不需要调用，直接 while 循环循环就可以把所有的中间件走一遍了。
根本不需要 next 来移交控制权。

实际上 express 里面的 while 和你这里的 while 不是同一个意思。

建议修改或注释。

> 被这个简化代码坑了半天...

**Comment by nanjixiong218** [comment]
你说的对，好久没看github了，不好意思，给你造成困扰
